### ISSUE TITLE
radiation pressure on shell

### ISSUE THREAD

**Issue by jacluff1** [ASU-CompMethodsPhysics-PHY494/final-2017-beta-team#4]
a function needs to be written that calculates $\chi_{\gamma,j}$, the fraction of photons that will hit a gas particle in shell $j$.

**Comment by jacluff1** [comment]
I am thinking that the radiation pressure on an object shell comes only from the agent shell directly encompassed by the object shell. This may be wrong or may be too simple.

**Comment by orbeckst** [comment]
You can always try very simple assumptions. Just make sure that you document them. Your Methods section should state clearly what your simplifying assumptions are.

**Comment by jacluff1** [comment]
Thanks. In the actual code I am writing I am documenting the
simplifications and why I am making them and why I think they will work so
I can keep track of what I'm doing as I'm building the model. With this one
I haven't completely figured it out am trying to communicate with my other
team mate. Thanks for the suggestion.

Peace and long life,
Jacob Cluff
jacluff1@asu.edu
602-503-9202
